name: nowa_aplikacja_pracy
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.0
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  awesome_dialog: ^3.2.1
  shared_preferences: ^2.2.2
  logging: ^1.2.0
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_dialogs: ^3.0.0
  fluttertoast: ^8.0.9
  material_color_utilities: ^0.11.1
  simple_animations: ^5.1.0
  fl_chart: ^0.66.1
  flutter_neumorphic:
    git:
      url: https://github.com/Idean/Flutter-Neumorphic.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/mammoth.png
